#! /bin/sh
# yum_proxyd     yum_proxyd startup script
#
# chkconfig: - 85 15
# description: yum_proxyd
#              
# Generated on Thu Jul 25 09:48:32 2013 by $Id: initd_gen 25414 2012-10-04 15:13:56Z andrew.canaday $

# Standard environment:
export YUM_PROXYD_HOME="/usr/local/"
export YUM_PROXYD_PID_FILE=${YUM_PROXYD_PID_FILE-"/var/run/yum_proxyd/yum_proxyd.pid"}
export YUM_PROXYD_OUT_FILE=${YUM_PROXYD_OUT_FILE-"/var/log/yum_proxyd/yum_proxyd.out"}
export YUM_PROXYD_ARGS=" --conf /etc/yum_proxyd/yum_proxyd.ini "
PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:${YUM_PROXYD_HOME}/sbin"
export NODE_PATH="${NODE_PATH}:/usr/local/lib/node_modules:${YUM_PROXYD_HOME}/lib/node_modules"

# Service Info:
DESC="yum_proxyd daemon"
NAME="yum_proxyd"
YUM_PROXYD_BIN="${YUM_PROXYD_HOME}/sbin/yum_proxyd"
SCRIPTNAME="/etc/init.d/${NAME}"

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

mkdir -p $( dirname ${YUM_PROXYD_PID_FILE} )
mkdir -p $( dirname ${YUM_PROXYD_OUT_FILE} )

# Functions:
yum_proxyd_pid=""
if [ -e "${YUM_PROXYD_PID_FILE}" ]; then
    yum_proxyd_pid=$( cat ${YUM_PROXYD_PID_FILE} )
fi

d_is_running() {
    if [ -n "${yum_proxyd_pid}" ]; then
        kill -0 ${yum_proxyd_pid} >/dev/null 2>&1
    else
        return 1
    fi
}

d_start() {

  # Bail if we're running:
  if d_is_running ; then
    echo -en "\n already running"
    return 0
  fi

  nohup ${YUM_PROXYD_BIN} ${YUM_PROXYD_ARGS} >> ${YUM_PROXYD_OUT_FILE} 2>&1 &
  echo $! > ${YUM_PROXYD_PID_FILE}
}

d_stop() {
  if d_is_running; then
    kill -s TERM ${yum_proxyd_pid} || echo -en "\n not running"
  fi
}

d_reload() {
  if d_is_running; then
    kill -s HUP ${yum_proxyd_pid} || echo -en "\n not running"
  fi
}


# Main:
case "$1" in
  start)
    echo -n "Starting $DESC: $NAME"
    d_start
        echo "."
  ;;
  stop)
    echo -n "Stopping $DESC: $NAME"
    d_stop
        echo "."
  ;;
  reload)
    echo -n "Reloading $DESC configuration..."
    d_reload
        echo "."
  ;;
  restart)
    echo -n "Restarting $DESC: $NAME"
    d_stop
    sleep 1
    d_start
    echo "."
  ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|reload}" >&2
    exit 1
  ;;
esac

exit 0
# EOF
